# Generated by Django 3.2.5 on 2021-07-30 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210727_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biographi',
            field=models.TextField(blank=True, help_text='Введите биографию автора', max_length=1000, null=True, verbose_name='Биография автора'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='Книга'),
        ),
    ]
